// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: _common.proto
#ifndef GRPC__5fcommon_2eproto__INCLUDED
#define GRPC__5fcommon_2eproto__INCLUDED

#include "_common.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace guldan {

}  // namespace guldan


#endif  // GRPC__5fcommon_2eproto__INCLUDED
