// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: player.proto

#include "player.pb.h"
#include "player.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace guldan {

static const char* Player_method_names[] = {
  "/guldan.Player/IsTwoHandUsed",
};

std::unique_ptr< Player::Stub> Player::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Player::Stub> stub(new Player::Stub(channel));
  return stub;
}

Player::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_IsTwoHandUsed_(Player_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Player::Stub::IsTwoHandUsed(::grpc::ClientContext* context, const ::guldan::EmptyRequest& request, ::guldan::BoolResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_IsTwoHandUsed_, context, request, response);
}

void Player::Stub::experimental_async::IsTwoHandUsed(::grpc::ClientContext* context, const ::guldan::EmptyRequest* request, ::guldan::BoolResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_IsTwoHandUsed_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::guldan::BoolResponse>* Player::Stub::AsyncIsTwoHandUsedRaw(::grpc::ClientContext* context, const ::guldan::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::guldan::BoolResponse>::Create(channel_.get(), cq, rpcmethod_IsTwoHandUsed_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::guldan::BoolResponse>* Player::Stub::PrepareAsyncIsTwoHandUsedRaw(::grpc::ClientContext* context, const ::guldan::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::guldan::BoolResponse>::Create(channel_.get(), cq, rpcmethod_IsTwoHandUsed_, context, request, false);
}

Player::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Player_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Player::Service, ::guldan::EmptyRequest, ::guldan::BoolResponse>(
          std::mem_fn(&Player::Service::IsTwoHandUsed), this)));
}

Player::Service::~Service() {
}

::grpc::Status Player::Service::IsTwoHandUsed(::grpc::ServerContext* context, const ::guldan::EmptyRequest* request, ::guldan::BoolResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace guldan

